###
POST localhost:8080/api/v1/document/
Content-Type: application/json

{
  "author": "kosad",
  "title": "ERT"
}

###
GET localhost:8080/api/v1/document/10
Content-Type: application/json

###
GET localhost:8080/api/v1/documents/package?documentsId=10,12,13
Content-Type: application/json