###
GET localhost:8080/api/v1/document/20
Content-Type: application/json

###
GET localhost:8080/api/v1/documents/package?documentsId=26,28
Content-Type: application/json

###
GET localhost:8080/api/v1/documents
Content-Type: application/json

{
  "author": "kosad"
}

###
POST localhost:8080/api/v1/document/
Content-Type: application/json

{
  "author": "Anastasiia",
  "title": "New Document"
}

###
PUT localhost:8080/api/v1/documents/21,26,28
Content-Type: application/json

###
PUT localhost:8080/api/v1/documents/approval/21,26,28
Content-Type: application/json

